from __future__ import annotations

import csv
import io
import json
from collections import Counter, defaultdict
from datetime import datetime
from typing import Any, Dict, Iterable, List

import streamlit as st

from app_paths import ANALYTICS_LOG_FILE, FAV_FILE
from analytics import track_event_once
from ui_theme import inject_global_css, show_global_footer, show_page_intro


# ============================================================
# Optional password gate (admin-only access)
# ============================================================
def require_stats_password() -> None:
    """
    Optional password gate for the statistics page.

    - If STATS_PASSWORD is not configured: show an info message and allow access.
    - If STATS_PASSWORD is configured:
        * If not authenticated yet, show a password form and block the page.
        * If already authenticated in this session, do nothing.
    """
    try:
        admin_password = st.secrets.get("STATS_PASSWORD", "")
    except Exception:
        admin_password = ""

    # Case 1: no password configured → allow and show info
    if not admin_password:
        st.info(
            "Statistics are visible because no admin password is configured. "
            "To restrict access, set `STATS_PASSWORD` in `.streamlit/secrets.toml`."
        )
        return

    # Case 2: already authenticated in this session
    if st.session_state.get("stats_admin_ok", False):
        return

    # Case 3: require authentication
    st.markdown("#### Admin access required")
    pwd = st.text_input("Enter statistics password", type="password")

    # No password typed yet → block further execution
    if not pwd:
        st.stop()

    # Wrong password → block further execution
    if pwd != admin_password:
        st.error("Incorrect password.")
        st.stop()

    # Correct password → mark as authenticated and rerun to clear the form
    st.session_state["stats_admin_ok"] = True
    st.rerun()


# ============================================================
# Page config & theme
# ============================================================
st.set_page_config(
    page_title="Statistics — Usage analytics (local, anonymous)",
    page_icon="📊",
    layout="wide",
)

inject_global_css()

# Local layout tweaks for the Statistics / admin page
st.markdown(
    """
    <style>
    /* Make st.metric values a bit smaller on this page */
    div[data-testid="stMetricValue"] {
        font-size: 1.8rem;
    }

    /* Slightly reduce the metric label as well */
    div[data-testid="stMetricLabel"] {
        font-size: 0.9rem;
    }

    /* Move main page content a bit up */
    div.block-container {
        padding-top: 1.8rem;
    }

    /* Reduce top margin of the first H1 (if any) */
    div.block-container h1:first-of-type {
        margin-top: 0.3rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# Password gate – if it fails, execution stops here
require_stats_password()

# Intro section (only shown after passing the gate)
show_page_intro(
    "Usage statistics for Rijksmuseum Explorer (local & anonymous). This dashboard is for internal review only:",
    [
        "Reads the local analytics JSONL file generated by the app (no external tracking).",
        "Shows usage counters and top lists (searches, page views, exports).",
        "Allows CSV export for further analysis in tools like Power BI or Tableau.",
    ],
)

st.markdown("## 📊 Usage statistics (local, anonymous)")
st.caption(
    "This dashboard reads the local file `analytics_events.json` created by the app. "
    "No data is sent anywhere."
)

# Page view (once) – only after passing the gate
track_event_once(
    event="page_view",
    page="Statistics",
    once_key="page_view::Statistics",
    props={},
)


# ============================================================
# Helpers
# ============================================================
def _read_jsonl(path) -> List[Dict[str, Any]]:
    """Best-effort read of JSONL analytics file."""
    events: List[Dict[str, Any]] = []
    try:
        if path.exists():
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        ev = json.loads(line)
                        if isinstance(ev, dict):
                            events.append(ev)
                    except Exception:
                        continue
    except Exception:
        return []
    return events


def _load_favorites_count() -> int:
    """Return how many artworks are currently in favorites.json."""
    try:
        if FAV_FILE.exists():
            with open(FAV_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                return len(data)
    except Exception:
        pass
    return 0


def _parse_timestamp(ev: Dict[str, Any]) -> datetime | None:
    """Try to parse the event timestamp (ISO string) into a datetime."""
    ts = ev.get("timestamp")
    if not isinstance(ts, str):
        return None
    try:
        # Remove trailing 'Z' if present (common ISO-8601 variant)
        return datetime.fromisoformat(ts.replace("Z", ""))
    except Exception:
        return None


def _flatten_events_to_csv(events: Iterable[Dict[str, Any]]) -> str:
    """
    Convert events list to CSV string.

    Columns:
        timestamp, event, page, props (JSON)
    """
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["timestamp", "event", "page", "props_json"])

    for ev in events:
        if not isinstance(ev, dict):
            continue
        ts = ev.get("timestamp", "")
        event_name = ev.get("event", "")
        page = ev.get("page", "")
        props = ev.get("props", {})
        try:
            props_str = json.dumps(props, ensure_ascii=False)
        except Exception:
            props_str = "{}"
        writer.writerow([ts, event_name, page, props_str])

    return output.getvalue()


def _aggregated_stats_to_csv(
    event_counts: Counter,
    search_queries: Counter,
    top_artworks: List[tuple[str, int]],
    top_artists: List[tuple[str, int]],
) -> str:
    """
    Build a simple aggregated CSV with multiple sections.

    Sections are separated by blank lines.
    """
    out = io.StringIO()
    writer = csv.writer(out)

    # Section 1: events by type
    writer.writerow(["Section", "Key", "Value"])
    for evt, cnt in event_counts.most_common():
        writer.writerow(["event_type", evt, cnt])

    writer.writerow([])

    # Section 2: top search queries
    for q, cnt in search_queries.most_common(50):
        writer.writerow(["search_query", q, cnt])

    writer.writerow([])

    # Section 3: top artworks
    for obj_id, cnt in top_artworks:
        writer.writerow(["artwork", obj_id, cnt])

    writer.writerow([])

    # Section 4: top artists
    for artist, cnt in top_artists:
        writer.writerow(["artist", artist, cnt])

    return out.getvalue()


def _format_dt_local(dt: datetime | None) -> str:
    """
    Receive a datetime (UTC or naive) and return a short string
    in local time, without microseconds.
    """
    if dt is None:
        return "—"

    try:
        local_dt = dt.astimezone()  # Use system timezone (e.g. Europe/Amsterdam)
        return local_dt.strftime("%Y-%m-%d %H:%M")
    except Exception:
        return str(dt)


# ============================================================
# Load events (file + session)
# ============================================================
session_events = st.session_state.get("_analytics_events", [])
file_events = _read_jsonl(ANALYTICS_LOG_FILE)

# Debug/context about the analytics file
debug_str = (
    f"DEBUG file: `{ANALYTICS_LOG_FILE}` | "
    f"exists={ANALYTICS_LOG_FILE.exists()} "
)

if ANALYTICS_LOG_FILE.exists():
    try:
        stat = ANALYTICS_LOG_FILE.stat()
        debug_str += (
            f"| size={stat.st_size} bytes | "
            f"mtime={datetime.fromtimestamp(stat.st_mtime)}"
        )
    except Exception:
        pass

st.caption(debug_str)

# Decide which events we use as the main source
if file_events:
    events = file_events
    source_label = "file (persistent)"
else:
    events = session_events
    source_label = "session (current run only)"

if not events:
    st.info("No analytics events recorded yet. Use the app and come back here.")
    st.stop()

# ============================================================
# Basic high-level metrics
# ============================================================
all_event_names = [e.get("event") for e in events if isinstance(e, dict)]
event_counts = Counter(all_event_names)

timestamps = [_parse_timestamp(e) for e in events]
timestamps = [t for t in timestamps if t is not None]
first_event = min(timestamps) if timestamps else None
last_event = max(timestamps) if timestamps else None

col_a, col_b, col_c, col_d = st.columns(4)
col_a.metric("Total events", value=len(events))
col_b.metric("Event types", value=len(event_counts))
col_c.metric("Source", value=source_label)
col_d.metric("Saved artworks (favorites.json)", value=_load_favorites_count())

col_e, col_f = st.columns(2)
col_e.metric("First event", value=_format_dt_local(first_event))
col_f.metric("Last event", value=_format_dt_local(last_event))

# ============================================================
# Event type filter
# ============================================================
unique_events = sorted(event_counts.keys())
st.markdown("### Filter by event type")
selected_types = st.multiselect(
    "Select which event types to include",
    options=unique_events,
    default=unique_events,
)

if selected_types:
    filtered_events = [
        e
        for e in events
        if isinstance(e, dict) and e.get("event") in selected_types
    ]
else:
    filtered_events = events

if not filtered_events:
    st.warning("No events after applying this filter.")
    st.stop()

filtered_counts = Counter(
    e.get("event") for e in filtered_events if isinstance(e, dict)
)

# ============================================================
# Download buttons (events & aggregated)
# ============================================================
st.markdown("### Export analytics")

events_csv = _flatten_events_to_csv(filtered_events)

# Aggregated stats will be filled after we compute them
aggregated_csv: str | None = None

col_dl1, col_dl2 = st.columns(2)
with col_dl1:
    st.download_button(
        "📄 Download events (CSV)",
        data=events_csv,
        file_name="rijks_explorer_events.csv",
        mime="text/csv",
        use_container_width=True,
    )

# ============================================================
# Aggregated views
# ============================================================
st.markdown("### Events by type")
for evt, cnt in filtered_counts.most_common():
    st.write(f"- **{evt}**: {cnt}")

# --- Exports by format ---
st.markdown("### Exports by format")
exports_by_format = Counter()
for e in filtered_events:
    if not isinstance(e, dict):
        continue
    if e.get("event") not in ("export_download", "export_prepare"):
        continue
    props = e.get("props") or {}
    fmt = props.get("format") or "unknown"
    exports_by_format[str(fmt)] += 1

if not exports_by_format:
    st.caption("No export events recorded yet.")
else:
    for fmt, cnt in exports_by_format.most_common():
        st.write(f"- **{fmt}**: {cnt}")

# --- Page views by page ---
st.markdown("### Page views by page")
page_views = Counter()
for e in filtered_events:
    if not isinstance(e, dict):
        continue
    if e.get("event") != "page_view":
        continue
    page_name = e.get("page") or "unknown"
    page_views[str(page_name)] += 1

if not page_views:
    st.caption("No page_view events recorded yet.")
else:
    for page_name, cnt in page_views.most_common():
        st.write(f"- **{page_name}**: {cnt}")

# --- Top search queries ---
st.markdown("### Top search queries")

search_queries = Counter()
for e in filtered_events:
    if not isinstance(e, dict):
        continue
    if e.get("event") != "search_executed":
        continue
    props = e.get("props") or {}
    q = props.get("query_sample") or props.get("query") or ""
    if not isinstance(q, str):
        continue
    q = q.strip()
    if not q:
        continue
    search_queries[q] += 1

max_queries = st.slider(
    "How many queries to show", min_value=5, max_value=50, value=10
)
if not search_queries:
    st.caption("No search_executed events recorded yet.")
else:
    for q, cnt in search_queries.most_common(max_queries):
        st.write(f"- **{q}**: {cnt}")

# --- Top artworks (views) ---
st.markdown("### Top artworks (views)")

views_by_object = defaultdict(int)
artist_by_object = defaultdict(str)

for e in filtered_events:
    if not isinstance(e, dict):
        continue
    if e.get("event") != "artwork_view":
        continue
    props = e.get("props") or {}
    obj_id = props.get("object_id")
    artist = props.get("artist")
    if isinstance(obj_id, str) and obj_id.strip():
        views_by_object[obj_id] += 1
        if isinstance(artist, str) and artist.strip():
            artist_by_object[obj_id] = artist.strip()

max_artworks = st.slider(
    "How many artworks to show", min_value=5, max_value=50, value=15
)
top_artworks_list = sorted(
    views_by_object.items(), key=lambda x: x[1], reverse=True
)[:max_artworks]

if not top_artworks_list:
    st.caption("No artwork_view events recorded yet.")
else:
    for obj_id, cnt in top_artworks_list:
        artist = artist_by_object.get(obj_id, "Unknown artist")
        st.write(f"- `{obj_id}` — **{artist}**: {cnt} view(s)")

# --- Top artists (views) ---
st.markdown("### Top artists (views)")

views_by_artist = Counter()
for obj_id, cnt in views_by_object.items():
    artist = artist_by_object.get(obj_id, "Unknown artist")
    views_by_artist[artist] += cnt

max_artists = st.slider(
    "How many artists to show", min_value=5, max_value=50, value=15
)
top_artists_list = views_by_artist.most_common(max_artists)

if not top_artists_list:
    st.caption("No artwork_view events recorded yet.")
else:
    for artist, cnt in top_artists_list:
        st.write(f"- **{artist}**: {cnt} view(s)")

# Now that we have all aggregates, build the aggregated CSV
aggregated_csv = _aggregated_stats_to_csv(
    filtered_counts,
    search_queries,
    top_artworks_list,
    top_artists_list,
)

with col_dl2:
    st.download_button(
        "📊 Download aggregated stats (CSV)",
        data=aggregated_csv,
        file_name="rijks_explorer_aggregated_stats.csv",
        mime="text/csv",
        use_container_width=True,
    )

# ============================================================
# Maintenance: clear analytics
# ============================================================
st.markdown("---")
st.markdown("### Danger zone")

# First click: only activates confirmation mode
clear_analytics_clicked = st.button(
    "🧹 Clear analytics log",
    help="Delete all locally stored analytics events (JSONL file + session).",
    key="btn_clear_analytics_log",
)

if clear_analytics_clicked:
    st.session_state["confirm_clear_analytics_log"] = True

# If confirmation mode is active, show the warning and buttons
if st.session_state.get("confirm_clear_analytics_log", False):
    st.warning(
        "This action will delete **all analytics events** stored locally "
        "(the JSONL file and the in-memory buffer). "
        "This cannot be undone.",
        icon="⚠️",
    )

    col_yes, col_no = st.columns(2)

    with col_yes:
        confirm_clear_analytics = st.button(
            "Yes, delete all analytics",
            key="btn_confirm_clear_analytics_log",
        )

    with col_no:
        cancel_clear_analytics = st.button(
            "Cancel",
            key="btn_cancel_clear_analytics_log",
        )

    if confirm_clear_analytics:
        # 1) Clear in-memory buffer
        st.session_state["_analytics_events"] = []

        # 2) Clear JSONL file on disk
        try:
            with open(ANALYTICS_LOG_FILE, "w", encoding="utf-8") as f:
                f.write("")
        except Exception:
            # Do not break UI if something goes wrong
            pass

        # 3) Reset confirmation flag
        st.session_state["confirm_clear_analytics_log"] = False

        st.success("All analytics events have been cleared.")
        st.rerun()

    elif cancel_clear_analytics:
        # User canceled the "clear analytics" action
        st.session_state["confirm_clear_analytics_log"] = False
        st.info("Analytics log was not cleared.")
        st.rerun()

# ============================================================
# Footer
# ============================================================
show_global_footer()